name: invoice_list_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: ^3.9.0

dependencies:
  #STATES MANAGEMENT
  flutter_riverpod: ^2.3.6
  hooks_riverpod: ^2.3.7
  flutter_hooks: ^0.20.5

  #NAVIGATION
  go_router: ^14.7.1

  # UI UTILITY
  animate_do: ^3.3.3
  flutter_spinkit: ^5.2.1

  # NETWORK
  # connectivity_plus: ^6.0.3
  # dart_ping: ^9.0.1
  dio: ^5.3.0

   # UTILS
  shared_preferences: ^2.2.0
  formz: ^0.8.0
  flutter_otp_text_field: ^1.1.3+2
  flutter_launcher_icons: ^0.14.3
  auto_size_text: ^3.0.0


  flutter:
    sdk: flutter
  intl: ^0.20.2

  # Loading
  shimmer: ^3.0.0
  google_fonts: ^6.3.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
